$(document).ready(function(){
  var sfx = document.getElementById('click_sfx');
  $('#home_cube').click(function(){
    sfx.play();
      setTimeout(function(){
      window.location.href="home.html"},1200);    
  });
  $('#anthem_cube').click(function(){
    sfx.play();
      setTimeout(function(){
      window.location.href="https://www.ea.com/ko-kr/games/anthem/about"},1200);    
  });
  $('#faction_cube').click(function(){
    sfx.play();
      setTimeout(function(){
      window.location.href="#"},1200);    
  });
  $('#javelin_cube').click(function(){
    sfx.play();
      setTimeout(function(){
      window.location.href="#"},1200);    
  });
  $('#info_cube').click(function(){
    sfx.play();
      setTimeout(function(){
      window.location.href="#"},1200);    
  });
  $('#trailer_cube').click(function(){
    sfx.play();
      setTimeout(function(){
      window.location.href="trailer.html"},1200);    
  });
});    